/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 care.gltf --transform
Author: bossdeff (https://sketchfab.com/bossdeff)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-lab-machine-675ae30eaa30470c995023b079569f34
Title: Sci-Fi Lab Machine
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Care(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/care-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Bed" position={[0, 22.228, -2.646]} rotation={[-1.462, 0, 0]} scale={100}>
            <mesh name="Bed_Op_Table_0" geometry={nodes.Bed_Op_Table_0.geometry} material={materials.Op_Table} />
          </group>
          <group name="Vilidius_Screen" position={[-72.583, 111.064, -160.086]} rotation={[-0.771, -1.063, 2.438]} scale={100}>
            <mesh name="Vilidius_Screen_Op_Table_0" geometry={nodes.Vilidius_Screen_Op_Table_0.geometry} material={materials.Op_Table} />
          </group>
        </group>
        <mesh name="cables_Op_Table_0" geometry={nodes.cables_Op_Table_0.geometry} material={materials.Op_Table} position={[-0.229, 0.288, -1.083]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="cables_Red_Wire_0" geometry={nodes.cables_Red_Wire_0.geometry} material={materials.PaletteMaterial001} position={[-0.229, 0.288, -1.083]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Cylinder_Machine_Emission_0" geometry={nodes.Cylinder_Machine_Emission_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.883, -1.015]} />
      </group>
    </group>
  )
}

useGLTF.preload('/care-transformed.glb')
